apiVersion: v1
kind: Pod
metadata:
  name: dotnet-diag-sample
spec:
  shareProcessNamespace: true
  securityContext:
    fsGroup: 1654
    fsGroupChangePolicy: OnRootMismatch
  containers:
    - name: sample-app
      image: ghcr.io/owner/repository/sample-app:latest
      securityContext:
        runAsUser: 1654
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
  volumes:
    - name: diagnostics
      emptyDir: {}
