apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  shareProcessNamespace: true
  securityContext:
    runAsUser: 1654
  containers:
    - name: app
      image: ghcr.io/OWNER/REPO/app:latest
      env:
        - name: DOTNET_DiagnosticPorts
          value: /diag/dotnet-diagnostic.sock,suspend=n,listen
      volumeMounts:
        - name: diagnostics
          mountPath: /diag
    - name: diag
      image: ghcr.io/koepalex/dotnet-k8s-debug-containers/diag/diag:latest
      stdin: true
      tty: true
      volumeMounts:
        - name: diagnostics
          mountPath: /diag
  volumes:
    - name: diagnostics
      emptyDir: {}
